### PR TITLE
Add new-cap exceptions

### LINKED ISSUE #14: Ember.A issues
Whenever I use `A()` I get errors like this:

```
A function with a name starting with an uppercase letter should only be used as a constructor
```

### PR DESCRIPTION
**Pull request by rwwagner90**
I just added the config @alexlafroscia gave us earlier

Resolves #14

### CODE REVIEW

**Comment by brzpegasus** [comment]
Thanks! I would just keep `Ember.A` and remove the other two. `$.Deferred` is not that commonly used, and `RSVP.hash` isn't a constructor so it shouldn't need to get invoked with `new`. If anyone has something more specific, they can always provide overrides in their own projects.

**Comment by rwwagner90** [comment]
Okay, makes sense. I just set it to do `A`.

**Comment by brzpegasus** [comment]
:+1: Could you also squash the two commits into one? Keeps the git history clean. I only keep separate commits in PRs if they are logically distinct.

**Comment by rwwagner90** [comment]
@brzpegasus GitHub has an option to squash PRs are you merge them in, could we enable that?

**Comment by brzpegasus** [comment]
That worked out well actually! Forgot about that. 😃

**Comment by rwwagner90** [comment]
Awesome 😃 . Thanks @brzpegasus!

**Comment by rwwagner90** [comment]
@brzpegasus would you mind releasing a new version with this change and the destructuring fixes @alexlafroscia implemented?

**Comment by brzpegasus** [comment]
Yup, was about to do that but got interrupted due to 👶 💩 .

**Comment by rwwagner90** [comment]
Haha well no rush. Just let me know when it's released 👍

**Comment by brzpegasus** [comment]
It's released now.

**Comment by rwwagner90** [comment]
🎉

**Pull request merged**
